@CdArchiveBackend_HostAddress = https://127.0.0.1

GET {{CdArchiveBackend_HostAddress}}/api

###
POST {{CdArchiveBackend_HostAddress}}/api/auth/login
Content-Type: application/json
{
    "username": "asd",
    "password": "12345678"
}

###
GET {{CdArchiveBackend_HostAddress}}/api/records

###
GET {{CdArchiveBackend_HostAddress}}/debug/routes